version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: syrotnik_cv
  MYSQL_USER: syrotnik
  MYSQL_PASSWORD: 123456

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      # MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      # MYSQL_HOST: mysql_db

  api:
    build:
      dockerfile: Dockerfile
      context: "./back"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./back:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syrotnik-cv-api.entrypoints=websecure"
      - "traefik.http.routers.syrotnik-cv-api.rule=Host(`cv.adrien-syrotnik.fr`) && PathPrefix(/api)"
      - "traefik.http.services.syrotnik-cv-api.loadbalancer.server.port=80"
      - "traefik.http.routers.syrotnik-cv-api.tls.certresolver=production"
      - "traefik.http.routers.syrotnik-cv-api.service=syrotnik-cv-api"

  front:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./front
    volumes:
      - /app/node_modules
      - ./front:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syrotnik-cv-front.entrypoints=websecure"
      - "traefik.http.routers.syrotnik-cv-front.rule=Host(`cv.adrien-syrotnik.fr`)"
      - "traefik.http.services.syrotnik-cv-front.loadbalancer.server.port=80"
      - "traefik.http.routers.syrotnik-cv-front.tls.certresolver=production"
      - "traefik.http.routers.syrotnik-cv-front.service=syrotnik-cv-front"