version: '3.8'

x-common-variables: &common-variables
  DB_NAME: syrotnik_cv
  MYSQL_DATABASE: syrotnik_cv
  MYSQL_USER: syrotnik
  MYSQL_PASSWORD: 123456

services:
  mysql_db:
    build:
      dockerfile: Dockerfile
      context: "./"
    restart: always
    container_name: MySQL
    cap_add:
      - SYS_NICE
    volumes:
      - db_data:/var/lib/mysql:rw
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_HOST: mysql_db

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin   
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1

volumes:
    db_data: